name: Terraform Infrastructure

on:
  push:
    paths:
      - "terraform/**"
  pull_request:
    paths:
      - "terraform/**"

env:
  TF_VERSION: "1.6.6"
  TF_WORKING_DIR: terraform

jobs:
  terraform-ci:
    name: Terraform CI (validate & plan)
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        env: [infra-dev, infra-staging, infra-prod]
    env:
      TF_WORKSPACE: ${{ matrix.env }}
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Environment Setup (Terraform)
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: CodeLint (terraform fmt)
        run: terraform fmt -check -recursive

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: CodeLint (tflint)
        run: |
          tflint --init
          tflint

      - name: Terraform Init (CI)
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false

  terraform-cd:
    name: Terraform CD (apply)
    runs-on: ubuntu-latest
    needs: terraform-ci

    if: github.ref == 'refs/heads/main'

    strategy:
      fail-fast: false
      matrix:
        # For now we only deploy staging. In the future, add: [infra-dev, infra-prod]
        env: [infra-staging]
    env:
      TF_WORKSPACE: ${{ matrix.env }}
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init (CD)
        run: terraform init -input=false

      - name: Terraform Apply (${{ matrix.env }})
        run: terraform apply -auto-approve -input=false